from .IndexPage import IndexPage
from .ColorPage import ColorPage
from .ButtonPage import ButtonPage
from .RadioButtonPage import RadioButtonPage
from .CheckBoxPage import CheckBoxPage
from .TextBoxPage import TextBoxPage
from .ToastPage import ToastPage
from .ExtraDataSecondPage import ExtraDataSecondPage
from .ExtraDataFirstPage import ExtraDataFirstPage
from .ControlWithAnimationPage import ControlWithAnimationPage
from .WindowPage import WindowPage
